openapi: 3.0.0
info:
  title: HotPod API
  description: API for managing processes in HotPod, a lightweight process manager for containers.
  version: 1.0.0
servers:
  - url: http://localhost:8080
    description: Local development server
paths:
  /start:
    post:
      summary: Start a new process
      description: Starts a new process with the specified command. Optionally replaces the current process and sets environment variables.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                command:
                  type: string
                  description: The command to execute.
                  example: "python /app/my_script.py"
                replace:
                  type: boolean
                  description: Whether to replace the current process (if any).
                  example: true
                env:
                  type: array
                  description: Environment variables to pass to the process.
                  items:
                    type: string
                  example: ["MY_ENV_VAR=value1", "ANOTHER_ENV_VAR=value2"]
      responses:
        '200':
          description: Process started successfully.
          content:
            text/plain:
              schema:
                type: string
                example: "Process started successfully"
        '400':
          description: Invalid request body.
        '500':
          description: Failed to start the process.

  /stop:
    post:
      summary: Stop the current process
      description: Stops the currently running process.
      responses:
        '200':
          description: Process stopped successfully.
          content:
            text/plain:
              schema:
                type: string
                example: "Process stopped successfully"
        '500':
          description: Failed to stop the process.

  /process:
    put:
      summary: Update process configuration
      description: Updates the process manager's configuration, such as keep-alive, shell, and arguments.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                keepAlive:
                  type: boolean
                  description: Whether to enable keep-alive functionality.
                  example: true
                shell:
                  type: string
                  description: The shell to use for executing commands.
                  example: "bash"
                args:
                  type: array
                  description: Arguments to pass to the shell.
                  items:
                    type: string
                  example: ["-c"]
      responses:
        '200':
          description: Configuration updated successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  keepAlive:
                    type: boolean
                    example: true
                  shell:
                    type: string
                    example: "bash"
                  args:
                    type: array
                    items:
                      type: string
                    example: ["-c"]
        '400':
          description: Invalid request body.
        '500':
          description: Failed to update the configuration.